version: 2
jobs:
  build:
    docker:
      - image: 'circleci/golang:1.9'
    working_directory: /go/src/github.com/kamontat/go-error-manager
    steps:
      - checkout
      - run: mkdir -p "/tmp/test-results/error-manager"
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go get -v -t -d ./...
      - run: go get -u github.com/NeroINC/goconvey-junit-report
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - run: >-
          go test -gcflags=-l -cover -coverprofile=coverage.txt
          -covermode=atomic -v
      - run: 'bash <(curl -s https://codecov.io/bash)'
      - store_test_results:
          path: /tmp/test-results
